---
- name: install switch
  hosts: pvna2:pvna2pilot
  become: yes
  gather_facts: yes

  tasks:

  # so we can use this playbook for update, stop the existing service
  # and ignore errors - typically only thrown if it does not exist
  - name: stop socat-rfswitch
    service:
      name: socat-rfswitch
      state: stopped
    ignore_errors: true
    
  - name: stop websocat-rfswitch
    service:
      name: websocat-rfswitch
      state: stopped
    ignore_errors: true
    
  - name: install socat-rfswitch to usr/local/bin
    copy:
      src: ../files/socat-rfswitch
      dest: /usr/local/bin/socat-rfswitch
      owner: root
      group: root
      mode: a+x
      
  - name: install websocat-rfswitch to usr/local/bin
    copy:
      src: ../files/websocat-rfswitch
      dest: /usr/local/bin/websocat-rfswitch
      owner: root
      group: root
      mode: a+x
      
  - name: Copy socat-rfswitch service file 
    copy:
      src: ../services/socat-rfswitch.service
      dest: /etc/systemd/system/socat-rfswitch.service
      owner: root
      group: root
       
  - name: Copy websocat-rfswitch service file 
    copy:
      src: ../services/websocat-rfswitch.service
      dest: /etc/systemd/system/websocat-rfswitch.service
      owner: root
      group: root
      
  - name: Just force systemd to reread configs (2.4 and above)
    ansible.builtin.systemd:
      daemon_reload: yes
      
  # the order of starting these two services matters    
  - name: start websocat-rfswitch
    service:
      name: websocat-rfswitch
      state: started
      enabled: true  
      
  - name: start socat-rfswitch
    service:
      name: socat-rfswitch
      state: started
      enabled: true
      
    
      

